#!/usr/bin/env python3
"""Regenerate catalog.yaml from packages/*/package.yaml.

The catalog index is what the inari-server Catalog Service consumes: one entry
per package with name, version, channel, OCI ref, description, and category.
OCI refs point at GHCR; the channel tag is published alongside the version tag
by release-oci.yml.

Dependency-free (no PyYAML): package.yaml is a flat mapping of scalar
key: value pairs, and catalog.yaml is emitted directly.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "catalog.yaml"
OCI_BASE = "ghcr.io/7k-inari/catalog"

ENTRY_RE = re.compile(r"^(\w+):\s*(.*)$")


def read_package_meta(path: Path) -> dict:
    meta = {}
    for line in path.read_text().splitlines():
        m = ENTRY_RE.match(line)
        if m:
            meta[m.group(1)] = m.group(2).strip()
    return meta


def build(root: Path) -> list[dict]:
    packages = []
    packages_dir = root / "packages"
    if packages_dir.is_dir():
        for child in sorted(packages_dir.iterdir()):
            pkg_file = child / "package.yaml"
            if not (child.is_dir() and pkg_file.is_file()):
                continue
            meta = read_package_meta(pkg_file)
            name = child.name
            version = meta["version"]
            channel = meta.get("channel", "incubating")
            packages.append(
                {
                    "name": name,
                    "version": version,
                    "channel": channel,
                    "description": meta.get("description", ""),
                    "category": meta.get("category", "uncategorized"),
                    "ociRef": f"{OCI_BASE}/{name}:{version}",
                    "channelRef": f"{OCI_BASE}/{name}:{channel}",
                }
            )
    return packages


def render(packages: list[dict]) -> str:
    lines = [
        "# GENERATED by scripts/build-catalog-index.py — do not edit by hand.",
        "apiVersion: inari.dev/v1alpha1",
        "kind: CatalogIndex",
        "packages:",
    ]
    for p in packages:
        lines.append(f"  - name: {p['name']}")
        for key in ("version", "channel", "description", "category", "ociRef", "channelRef"):
            lines.append(f"    {key}: {p[key]}")
    return "\n".join(lines) + "\n"


def main() -> int:
    packages = build(ROOT)
    INDEX.write_text(render(packages))
    print(f"catalog.yaml: {len(packages)} package(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
