#!/usr/bin/env python3
"""Regenerate catalog.yaml from packages/*/package.yaml.

The catalog index is what the inari-server Catalog Service consumes: one entry
per package with name, version, channel, type, OCI ref, description, and
category. OCI refs point at GHCR; the channel tag is published alongside the
version tag by release-oci.yml.

Package types (package.yaml `type`, default `kro-rgd`):
- kro-rgd:      KRO ResourceGraphDefinition (rgd.yaml)
- platform-app: Helm chart wrapper installable on the platform cluster
- policy-pack:  admission policies (CEL ValidatingAdmissionPolicies)

Dependency-free (no PyYAML): package.yaml is a flat mapping of scalar
key: value pairs, and catalog.yaml is emitted directly.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "catalog.yaml"
OCI_BASE = "ghcr.io/7k-inari/catalog"

ENTRY_RE = re.compile(r"^(\w+):\s*(.*)$")
FOLDED_RE = re.compile(r"^[>|][+-]?$")


def read_package_meta(path: Path) -> dict:
    meta = {}
    lines = path.read_text().splitlines()
    i = 0
    while i < len(lines):
        m = ENTRY_RE.match(lines[i])
        if m:
            key, value = m.group(1), m.group(2).strip()
            if FOLDED_RE.match(value):
                parts = []
                i += 1
                while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                    parts.append(lines[i].strip())
                    i += 1
                value = " ".join(p for p in parts if p)
            else:
                i += 1
            meta[key] = value
            continue
        i += 1
    return meta


def build(root: Path) -> list[dict]:
    packages = []
    packages_dir = root / "packages"
    if packages_dir.is_dir():
        for child in sorted(packages_dir.iterdir()):
            pkg_file = child / "package.yaml"
            if not (child.is_dir() and pkg_file.is_file()):
                continue
            meta = read_package_meta(pkg_file)
            name = child.name
            version = meta["version"]
            channel = meta.get("channel", "incubating")
            packages.append(
                {
                    "name": name,
                    "version": version,
                    "channel": channel,
                    "type": meta.get("type", "kro-rgd"),
                    "description": meta.get("description", ""),
                    "category": meta.get("category", "uncategorized"),
                    "ociRef": f"{OCI_BASE}/{name}:{version}",
                    "channelRef": f"{OCI_BASE}/{name}:{channel}",
                }
            )
    return packages


def render(packages: list[dict]) -> str:
    lines = [
        "# GENERATED by scripts/build-catalog-index.py — do not edit by hand.",
        "apiVersion: inari.dev/v1alpha1",
        "kind: CatalogIndex",
        "packages:",
    ]
    for p in packages:
        lines.append(f"  - name: {p['name']}")
        for key in ("version", "channel", "type", "description", "category", "ociRef", "channelRef"):
            value = str(p[key]).replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    {key}: "{value}"')
    return "\n".join(lines) + "\n"


def main() -> int:
    packages = build(ROOT)
    INDEX.write_text(render(packages))
    print(f"catalog.yaml: {len(packages)} package(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
